# Generated by Django 4.2.1 on 2023-05-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_certificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wood',
            new_name='Good',
        ),
    ]
