# Generated by Django 4.2.1 on 2023-06-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='photo',
            field=models.ImageField(upload_to='wood-images/'),
        ),
    ]
