# Generated by Django 4.2.1 on 2023-06-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='placeholder.jpg', upload_to='news-images/'),
        ),
    ]
